#!/bin/sh
# npm run build
rsync -av ./ u97170284@217.160.196.7:~/SYMFONY --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*" --exclude=/vendor
ssh u97170284@217.160.196.7 'cd ~/SYMFONY && php bin/console cache:clear'